package:
  name: "morphman"
  version: "1.2"

source:
  path: ../

build:
  number: 1

requirements:
  build:
    - python
    - setuptools  # [win]

  run:
    - python {{ python }}
    - scipy
    - numpy {{ numpy }}
    - vtk {{ vtk }}
    - vmtk

test:
  requires:
    - pytest
  source_files:
    - ./test


about:
  home: https://github.com/KVSlab/morphMan
  summary: 'morphMan - morphological manipulation'
  license: GNU GPL 3.0
  license_file: LICENSE
  doc_url: https://morphman.readthedocs.io
